"use client";

import { BlogPostLayout } from "@/components/blog/blog-post-layout";
import { getBlogPost } from "@/content/blog-posts";

const post = getBlogPost("evaluations")!;

export default function EvaluationsPost() {
    return (
        <BlogPostLayout title={post.title} description={post.description} publishedAt={post.publishedAt}>
            <p>
                Performance reviews are universally hated. They're infrequent, heavily biased by recent events, and rarely reflect the nuanced reality of an employee's day-to-day impact. Mitable changes this by providing continuous, AI-driven evaluations that are rooted in objective data.
            </p>

            <h2>The Recency Bias Problem</h2>
            <p>
                When a manager sits down to write an annual review, they typically only remember the last month of work. If an employee had a stellar first half of the year but a quiet December, their review will disproportionately reflect December.
            </p>
            <p>
                Furthermore, subjective evaluations often punish employees who do critical "glue work"—mentoring juniors, reviewing code, or unblocking other teams—because this work isn't easily visible in a Jira board.
            </p>

            <h2>How Mitable Evaluates</h2>
            <p>
                Because our system captures work context across all apps (Slack, VS Code, Figma, Notion), our evaluation engine has a complete picture.
            </p>

            <h3>The Evaluation Pipeline</h3>
            <ol>
                <li><strong>Data Aggregation:</strong> We pull the comprehensive activity summaries generated by our AI analysis engine.</li>
                <li><strong>Benchmark Comparison:</strong> We run these summaries against the specific benchmarks defined for that employee's role.</li>
                <li><strong>Semantic Scoring:</strong> Using a powerful hybrid semantic search system, we pull similar past work to ensure scoring consistency.</li>
                <li><strong>Actionable Feedback:</strong> We don't just output a number. Mitable generates specific coaching nudges, like "You've been writing great code, but your PR reviews have dropped off this week."</li>
            </ol>

            <h2>Privacy and Trust</h2>
            <p>
                We believe evaluations should empower employees, not police them. Employees can see exactly which data points contributed to their score, and they can contest or add context to AI-generated summaries before their manager sees them.
            </p>
            <p>
                By automating the objective measurement of work, we free up managers to do what they do best: actually managing and mentoring their team.
            </p>
        </BlogPostLayout>
    );
}
