import {
  pgTable,
  uuid,
  varchar,
  text,
  jsonb,
  timestamp,
  integer,
  real,
  date,
  index,
  unique,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { users } from "../../domains/auth/schema/users.schema";
import { organizations } from "../../domains/auth/schema/organizations.schema";
import { monitoringSessions } from "./monitoring.schema";

/**
 * User Daily Activities
 *
 * Per-user daily rollup generated by the Day Analyzer RLM (Layer 1).
 * One row per user per day (or per period for weekly/monthly snapshots).
 * Contains aggregated metrics, AI summary, and links to activity_blocks.
 */
export const userDailyActivities = pgTable(
  "user_daily_activities",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),

    // The date this rollup covers
    activityDate: date("activity_date").notNull(),

    // Period type for time-period snapshots (Layer 3)
    periodType: varchar("period_type", { length: 20 }).notNull().default("daily"),

    // Quantitative rollup
    totalWorkMinutes: integer("total_work_minutes").notNull().default(0),
    totalMeetingMinutes: integer("total_meeting_minutes").notNull().default(0),
    totalActiveMinutes: integer("total_active_minutes").notNull().default(0),
    totalSessionMinutes: integer("total_session_minutes").notNull().default(0),
    totalSessions: integer("total_sessions").notNull().default(0),
    totalCaptures: integer("total_captures").notNull().default(0),

    // Percentage breakdowns
    workPercentage: real("work_percentage").notNull().default(0),
    meetingPercentage: real("meeting_percentage").notNull().default(0),

    // App usage breakdown (JSONB array)
    appBreakdown: jsonb("app_breakdown").notNull().default("[]"),

    // Activity category breakdown (JSONB array)
    categoryBreakdown: jsonb("category_breakdown").notNull().default("[]"),

    // Topic & subscriber breakdowns (JSONB arrays)
    topicBreakdown: jsonb("topic_breakdown").default("[]"),
    subscriberBreakdown: jsonb("subscriber_breakdown").default("[]"),

    // AI-generated content (from Day Analyzer RLM)
    daySummary: text("day_summary"),
    keyAccomplishments: jsonb("key_accomplishments").notNull().default("[]"),

    // Tracking which sessions have been materialized into this day (idempotency)
    processedSessionIds: jsonb("processed_session_ids").notNull().default("[]"),

    // Processing metadata
    status: varchar("status", { length: 20 }).notNull().default("pending"),
    modelUsed: varchar("model_used", { length: 100 }),
    processingTimeMs: integer("processing_time_ms"),
    lastProcessedAt: timestamp("last_processed_at", { withTimezone: true }),
    errorMessage: text("error_message"),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    userDateIdx: index("idx_user_daily_activities_user").on(table.userId, table.activityDate),
    orgDateIdx: index("idx_user_daily_activities_org").on(table.organizationId, table.activityDate),
    statusIdx: index("idx_user_daily_activities_status").on(table.status),
    uniqueUserDatePeriod: unique().on(table.userId, table.activityDate, table.periodType),
  })
);

/**
 * Activity Blocks
 *
 * Individual work/meeting blocks within a user's day.
 * Generated by the Day Analyzer RLM as it reconstructs the daily timeline.
 * Each block has a name, time range, type (work/meeting), and rich metadata.
 */
export const activityBlocks = pgTable(
  "activity_blocks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    dailyActivityId: uuid("daily_activity_id")
      .notNull()
      .references(() => userDailyActivities.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // Block type and identity
    blockType: varchar("block_type", { length: 20 }).notNull(),
    name: varchar("name", { length: 500 }).notNull(),
    externalId: varchar("external_id", { length: 255 }),

    // Timing
    startTime: timestamp("start_time", { withTimezone: true }).notNull(),
    endTime: timestamp("end_time", { withTimezone: true }).notNull(),
    durationMinutes: integer("duration_minutes").notNull(),

    // Details
    description: text("description"),
    rawTranscript: text("raw_transcript"), // Full speaker-by-speaker transcript (for agent Q&A)
    apps: jsonb("apps").notNull().default("[]"),
    category: varchar("category", { length: 50 }),

    // Meeting-specific fields
    participants: jsonb("participants").default("[]"),

    // Source tracking
    sessionId: uuid("session_id").references(() => monitoringSessions.id, { onDelete: "set null" }),
    sourceSessionIds: jsonb("source_session_ids").notNull().default("[]"),

    // AI-extracted topic & subscriber (denormalized strings for GROUP BY queries)
    topicName: varchar("topic_name", { length: 200 }),
    subscriberName: varchar("subscriber_name", { length: 200 }),

    // Ordering within the day
    sequenceNumber: integer("sequence_number").notNull().default(0),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    dailyIdx: index("idx_activity_blocks_daily").on(table.dailyActivityId),
    userTimeIdx: index("idx_activity_blocks_user_time").on(table.userId, table.startTime),
    typeIdx: index("idx_activity_blocks_type").on(table.blockType),
  })
);

/**
 * Org Daily Metrics
 *
 * Org-wide aggregated metrics (Layer 2 output).
 * Computed from user_daily_activities by averaging/summing across all users.
 * Powers the admin Dashboard view.
 */
export const orgDailyMetrics = pgTable(
  "org_daily_metrics",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),

    // The date this rollup covers
    metricsDate: date("metrics_date").notNull(),

    // Period type for time-period snapshots (Layer 3)
    periodType: varchar("period_type", { length: 20 }).notNull().default("daily"),

    // Team-wide averages
    avgWorkMinutes: real("avg_work_minutes").notNull().default(0),
    avgMeetingMinutes: real("avg_meeting_minutes").notNull().default(0),
    avgActiveMinutes: real("avg_active_minutes").notNull().default(0),
    avgWorkPercentage: real("avg_work_percentage").notNull().default(0),
    avgMeetingPercentage: real("avg_meeting_percentage").notNull().default(0),

    // Totals
    totalUsersTracked: integer("total_users_tracked").notNull().default(0),
    totalTeamWorkMinutes: integer("total_team_work_minutes").notNull().default(0),
    totalTeamMeetingMinutes: integer("total_team_meeting_minutes").notNull().default(0),

    // Org-wide activity distribution (JSONB array)
    activityDistribution: jsonb("activity_distribution").notNull().default("[]"),

    // Top apps across org (JSONB array)
    topApps: jsonb("top_apps").notNull().default("[]"),

    // Per-user summary for quick access (JSONB array)
    userSummaries: jsonb("user_summaries").notNull().default("[]"),

    // Processing metadata
    lastProcessedAt: timestamp("last_processed_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    orgDateIdx: index("idx_org_daily_metrics_org").on(table.organizationId, table.metricsDate),
    uniqueOrgDatePeriod: unique().on(table.organizationId, table.metricsDate, table.periodType),
  })
);

// ============================================================================
// Relations
// ============================================================================

export const userDailyActivitiesRelations = relations(userDailyActivities, ({ one, many }) => ({
  user: one(users, {
    fields: [userDailyActivities.userId],
    references: [users.id],
  }),
  organization: one(organizations, {
    fields: [userDailyActivities.organizationId],
    references: [organizations.id],
  }),
  blocks: many(activityBlocks),
}));

export const activityBlocksRelations = relations(activityBlocks, ({ one }) => ({
  dailyActivity: one(userDailyActivities, {
    fields: [activityBlocks.dailyActivityId],
    references: [userDailyActivities.id],
  }),
  user: one(users, {
    fields: [activityBlocks.userId],
    references: [users.id],
  }),
}));

export const orgDailyMetricsRelations = relations(orgDailyMetrics, ({ one }) => ({
  organization: one(organizations, {
    fields: [orgDailyMetrics.organizationId],
    references: [organizations.id],
  }),
}));

// ============================================================================
// Export types
// ============================================================================

export type UserDailyActivity = typeof userDailyActivities.$inferSelect;
export type NewUserDailyActivity = typeof userDailyActivities.$inferInsert;
export type ActivityBlock = typeof activityBlocks.$inferSelect;
export type NewActivityBlock = typeof activityBlocks.$inferInsert;
export type OrgDailyMetric = typeof orgDailyMetrics.$inferSelect;
export type NewOrgDailyMetric = typeof orgDailyMetrics.$inferInsert;

// Helper types for JSONB fields
export interface AppBreakdownEntry {
  app: string;
  minutes: number;
}

export interface CategoryBreakdownEntry {
  category: string;
  percentage: number;
  minutes: number;
}

export interface OrgActivityDistributionEntry {
  category: string;
  percentage: number;
  totalMinutes: number;
}

export interface OrgTopAppEntry {
  app: string;
  totalMinutes: number;
  userCount: number;
}

export interface OrgUserSummaryEntry {
  userId: string;
  name: string;
  activeMinutes: number;
  workPct: number;
  meetingPct: number;
}

export interface TopicBreakdownEntry {
  topicName: string;
  minutes: number;
  percentage: number;
}

export interface SubscriberBreakdownEntry {
  subscriberName: string;
  minutes: number;
  percentage: number;
}
