import { slackService } from "./slack.service.js";
import { notionService } from "./notion.service.js";
import { embeddingService } from "./embedding.service.js";
import { vectorService } from "./vector.service.js";
import { chunkingService } from "./chunking.service.js";
import { notionChunkingService } from "./notion-chunking.service.js";
import { db } from "../db/client.js";
import * as schema from "../db/schema/index.js";
import { eq, and, sql, desc } from "drizzle-orm";
import type { VectorRecord } from "./vector.service.js";
import type { NewSearchContent } from "../db/schema/search-content.schema.js";

const SYNC_CONFIG = {
  MESSAGES_PER_PAGE: 100,
  BATCH_SIZE: 100,
} as const;

export interface SlackIntegrationMetadata {
  team_id?: string;
  team_name?: string;
  bot_user_id?: string;
  scope?: string;
  app_id?: string;
  selected_channels?: string[];
  // TODO: Define complete metadata structure
  [key: string]: any;
}

export interface NotionIntegrationMetadata {
  bot_id: string;
  workspace_id: string;
  workspace_name?: string;
  workspace_icon?: string;
  owner: any;
  duplicated_template_id?: string;
  // TODO: Add selected_pages if we want to filter
  [key: string]: any;
}

export interface IngestionProgress {
  channelsProcessed: number;
  totalChannels: number;
  messagesProcessed: number;
  messagesEmbedded: number;
  errors: string[];
  currentChannel?: string;
}

export interface IngestionResult {
  success: boolean;
  channelsProcessed: number;
  messagesEmbedded: number;
  totalMessages: number;
  errors: string[];
  duration: number;
}

class IngestionService {
  /**
   * Transform vector metadata to PostgreSQL searchContent format
   * Dual-write helper: Maps Pinecone vector metadata to PostgreSQL columns
   * Note: textVector is auto-generated by PostgreSQL trigger from text field
   */
  private transformVectorToSearchContent(
    vector: VectorRecord,
    organizationId: string
  ): NewSearchContent {
    const { id, metadata } = vector;

    // Extract timestamp - handle both seconds and milliseconds
    const timestamp = metadata.timestamp
      ? metadata.timestamp < 10000000000
        ? metadata.timestamp * 1000
        : metadata.timestamp
      : Date.now();

    return {
      id,
      organizationId,
      source: metadata.source || "unknown",
      sourceType: metadata.source_type,
      text: metadata.text || "",

      // textVector is populated by BEFORE INSERT trigger (update_search_content_text_vector)
      // We provide empty string as placeholder, trigger will override with to_tsvector('english', text)
      textVector: "",

      // Slack-specific fields
      channelId: metadata.channel_id,
      channelName: metadata.channel_name,
      userId: metadata.user_id,
      username: metadata.username,

      // Notion-specific fields (basic)
      pageId: metadata.page_id,
      pageTitle: metadata.page_title,
      blockId: metadata.block_id,
      blockType: metadata.block_type,
      
      // Notion-specific fields (structure-aware)
      sectionPath: metadata.section_path,
      sectionTitle: metadata.section_title,
      sectionId: metadata.section_id,
      headingLevel: metadata.heading_level,
      
      // Chunk classification
      chunkType: metadata.chunk_type,
      hasCode: metadata.has_code || false,
      hasTable: metadata.has_table || false,
      hasList: metadata.has_list || false,
      
      // Code-specific metadata
      codeLanguage: metadata.code_language,

      // Chunk metadata
      chunkIndex: metadata.chunk_index || 0,
      totalChunks: metadata.total_chunks || 1,
      isChunked: metadata.is_chunked || false,

      // Temporal metadata
      timestamp,
      date: metadata.date || new Date(timestamp).toISOString().split("T")[0],
    };
  }

  /**
   * Sync Slack messages for an organization
   * Fetches messages from selected channels, embeds them, and stores in BOTH Pinecone AND PostgreSQL
   */
  async syncSlackMessages(
    organizationId: string,
    onProgress?: (progress: IngestionProgress) => void
  ): Promise<IngestionResult> {
    const startTime = Date.now();
    const result: IngestionResult = {
      success: false,
      channelsProcessed: 0,
      messagesEmbedded: 0,
      totalMessages: 0,
      errors: [],
      duration: 0,
    };

    let syncLogId: string | null = null;

    try {
      // Get integration
      const [integration] = await db
        .select()
        .from(schema.integrations)
        .where(
          and(
            eq(schema.integrations.organizationId, organizationId),
            eq(schema.integrations.provider, "slack")
          )
        )
        .limit(1);

      if (!integration) {
        throw new Error("Slack integration not found");
      }

      // Get selected channels from metadata
      const metadata = integration.metadata as SlackIntegrationMetadata;
      const selectedChannels: string[] = metadata?.selected_channels || [];

      if (selectedChannels.length === 0) {
        throw new Error(
          "No channels selected for syncing. Please configure Slack integration first."
        );
      }

      // Create sync log
      const [syncLog] = await db
        .insert(schema.syncLogs)
        .values({
          integrationId: integration.id,
          status: "in_progress",
          itemsSynced: 0,
          startedAt: new Date(),
        })
        .returning();

      syncLogId = syncLog.id;

      // Get workspace info from metadata
      const workspaceId = metadata?.team_id || "unknown";
      const workspaceName = metadata?.team_name || "Slack Workspace";

      // Determine sync mode (incremental vs full)
      const [latestMessage] = await db
        .select({ timestamp: schema.searchContent.timestamp })
        .from(schema.searchContent)
        .where(
          and(
            eq(schema.searchContent.organizationId, organizationId),
            eq(schema.searchContent.source, "slack")
          )
        )
        .orderBy(desc(schema.searchContent.timestamp))
        .limit(1);

      let oldestTimestamp: string | undefined;
      let syncMode = "full";

      if (latestMessage?.timestamp) {
        // Convert to Unix timestamp string (seconds)
        oldestTimestamp = Math.floor(latestMessage.timestamp / 1000).toString();
        syncMode = "incremental";
        console.log(`🔄 Sync Mode: ${syncMode}`);
        console.log(`📅 Last sync: ${new Date(latestMessage.timestamp).toLocaleString()}`);
      } else {
        console.log(`🔄 Sync Mode: ${syncMode} (first sync)`);
      }

      // Process each channel
      for (let i = 0; i < selectedChannels.length; i++) {
        const channelId = selectedChannels[i];

        try {
          // Get channel info
          const channelInfo = await slackService.getChannelInfo(organizationId, channelId);
          const channelName = channelInfo?.name || channelId;

          // Update progress
          onProgress?.({
            channelsProcessed: i,
            totalChannels: selectedChannels.length,
            messagesProcessed: result.totalMessages,
            messagesEmbedded: result.messagesEmbedded,
            errors: result.errors,
            currentChannel: channelName,
          });

          // Fetch messages from channel with pagination
          let cursor: string | undefined;
          let channelMessageCount = 0;

          do {
            const { messages, nextCursor, hasMore } = await slackService.fetchChannelMessages(
              organizationId,
              channelId,
              cursor,
              SYNC_CONFIG.MESSAGES_PER_PAGE,
              oldestTimestamp
            );

            if (messages.length === 0) break;

            // Process messages in batches
            for (let j = 0; j < messages.length; j += SYNC_CONFIG.BATCH_SIZE) {
              const batch = messages.slice(j, j + SYNC_CONFIG.BATCH_SIZE);
              await this.processBatch(
                batch,
                organizationId,
                workspaceId,
                workspaceName,
                channelName,
                channelInfo?.is_private || false
              );

              result.messagesEmbedded += batch.length;
              channelMessageCount += batch.length;

              // Update progress
              onProgress?.({
                channelsProcessed: i,
                totalChannels: selectedChannels.length,
                messagesProcessed: result.totalMessages + channelMessageCount,
                messagesEmbedded: result.messagesEmbedded,
                errors: result.errors,
                currentChannel: channelName,
              });
            }

            result.totalMessages += messages.length;
            cursor = nextCursor;

            // Continue fetching until all messages are retrieved
            if (!hasMore) break;
          } while (cursor);

          result.channelsProcessed++;
        } catch (error) {
          const errorMsg = `Failed to process channel ${channelId}: ${
            error instanceof Error ? error.message : "Unknown error"
          }`;
          result.errors.push(errorMsg);
        }
      }

      // Update sync log
      await db
        .update(schema.syncLogs)
        .set({
          status: "success",
          itemsSynced: result.messagesEmbedded,
          completedAt: new Date(),
        })
        .where(eq(schema.syncLogs.id, syncLogId));

      // Update integration lastSyncedAt
      await db
        .update(schema.integrations)
        .set({
          lastSyncedAt: new Date(),
          updatedAt: new Date(),
        })
        .where(eq(schema.integrations.id, integration.id));

      result.success = true;
      result.duration = Date.now() - startTime;

      return result;
    } catch (error) {
      // Update sync log as failed
      if (syncLogId) {
        await db
          .update(schema.syncLogs)
          .set({
            status: "failed",
            errorMessage: error instanceof Error ? error.message : "Unknown error",
            completedAt: new Date(),
          })
          .where(eq(schema.syncLogs.id, syncLogId));
      }

      result.errors.push(error instanceof Error ? error.message : "Unknown error");
      result.duration = Date.now() - startTime;
      return result;
    }
  }

  /**
   * Process a batch of Slack messages: chunk, embed, and dual-write to Pinecone + PostgreSQL
   */
  private async processBatch(
    messages: any[],
    organizationId: string,
    workspaceId: string,
    workspaceName: string,
    channelName: string,
    isPrivate: boolean
  ): Promise<void> {
    const validMessages = messages.filter((msg) => msg.text && msg.text.trim().length > 0);

    if (validMessages.length === 0) return;

    try {
      // Check which messages already exist (Slack messages are immutable - once embedded, done forever)
      const existingMessages = await db
        .select({ id: schema.searchContent.id })
        .from(schema.searchContent)
        .where(
          and(
            eq(schema.searchContent.organizationId, organizationId),
            eq(schema.searchContent.source, "slack")
          )
        );
      
      const existingIds = new Set(existingMessages.map(m => {
        // Extract message TS from ID (format: slack-{channel}-{ts}-chunk-{index})
        const match = m.id.match(/slack-[^-]+-([^-]+)-chunk/);
        return match ? match[1] : null;
      }).filter(Boolean));

      // Filter out already-embedded messages
      const newMessages = validMessages.filter(msg => !existingIds.has(msg.ts));
      
      if (newMessages.length === 0) {
        console.log(`   ⏭️  All ${validMessages.length} messages already embedded - skipping`);
        return;
      }
      
      if (newMessages.length < validMessages.length) {
        console.log(`   📊 ${newMessages.length} new, ${validMessages.length - newMessages.length} already embedded`);
      }

      const allChunks: Array<{
        chunkText: string;
        chunkIndex: number;
        totalChunks: number;
        parentMessage: any;
      }> = [];

      for (const msg of newMessages) {
        const chunks = chunkingService.chunkText(msg.text);
        for (const chunk of chunks) {
          allChunks.push({
            chunkText: chunk.text,
            chunkIndex: chunk.chunkIndex,
            totalChunks: chunk.totalChunks,
            parentMessage: msg,
          });
        }
      }

      const texts = allChunks.map((c) => c.chunkText);
      const embeddings = await embeddingService.embedTexts(texts);

      const vectors = await Promise.all(
        allChunks.map(async (chunkData, idx) => {
          const msg = chunkData.parentMessage;
          const userInfo = await slackService.getUserInfo(organizationId, msg.user);
          const timestamp = parseFloat(msg.ts);
          const date = new Date(timestamp * 1000);

          return {
            id: `slack-${msg.channel}-${msg.ts}-chunk-${chunkData.chunkIndex}`,
            values: embeddings[idx],
            metadata: {
              text: chunkData.chunkText,
              source: "slack",
              source_type: msg.thread_ts ? "thread_reply" : "message",

              channel_id: msg.channel,
              channel_name: channelName,
              message_ts: msg.ts,
              ...(msg.thread_ts && { thread_ts: msg.thread_ts }),

              chunk_index: chunkData.chunkIndex,
              total_chunks: chunkData.totalChunks,
              is_chunked: chunkData.totalChunks > 1,

              user_id: msg.user,
              username: userInfo?.name || "unknown",
              user_real_name: userInfo?.real_name || "Unknown User",

              message_url: msg.permalink,

              timestamp: Math.floor(timestamp),
              date: date.toISOString().split("T")[0],
              year: date.getFullYear(),
              month: date.getMonth() + 1,
              day_of_week: date.toLocaleDateString("en-US", { weekday: "long" }),

              organization_id: organizationId,
              workspace_id: workspaceId,
              workspace_name: workspaceName,

              is_private_channel: isPrivate,
              channel_type: isPrivate ? "private_channel" : "public_channel",
            },
          };
        })
      );

      const namespace = `org-${organizationId}`;

      // DUAL-WRITE: Store in both Pinecone (semantic) and PostgreSQL (keyword)
      await vectorService.upsertVectors(vectors, namespace);

      // Transform vectors to PostgreSQL format and upsert (handles duplicates)
      const searchContentRecords = vectors.map((v) =>
        this.transformVectorToSearchContent(v, organizationId)
      );

      // Use onConflictDoUpdate to handle re-syncing of updated messages
      await db
        .insert(schema.searchContent)
        .values(searchContentRecords)
        .onConflictDoUpdate({
          target: schema.searchContent.id,
          set: {
            text: sql`EXCLUDED.text`,
            timestamp: sql`EXCLUDED.timestamp`,
            date: sql`EXCLUDED.date`,
            updatedAt: new Date(),
          },
        });
    } catch (error) {
      throw new Error("Failed to process message batch", { cause: error });
    }
  }

  /**
   * Sync Notion pages for an organization
   * Fetches all shared pages, embeds blocks, and stores in BOTH Pinecone AND PostgreSQL
   */
  async syncNotionPages(
    organizationId: string,
    onProgress?: (progress: IngestionProgress) => void
  ): Promise<IngestionResult> {
    const startTime = Date.now();
    const result: IngestionResult = {
      success: false,
      channelsProcessed: 0, // Using "channels" field for "pages" count
      messagesEmbedded: 0, // Using "messages" field for "blocks" count
      totalMessages: 0,
      errors: [],
      duration: 0,
    };

    let syncLogId: string | null = null;

    try {
      // Get integration
      const [integration] = await db
        .select()
        .from(schema.integrations)
        .where(
          and(
            eq(schema.integrations.organizationId, organizationId),
            eq(schema.integrations.provider, "notion")
          )
        )
        .limit(1);

      if (!integration) {
        throw new Error("Notion integration not found");
      }

      // Get workspace info from metadata
      const metadata = integration.metadata as NotionIntegrationMetadata;
      const workspaceId = metadata?.workspace_id || "unknown";
      const workspaceName = metadata?.workspace_name || "Notion Workspace";
      const botId = metadata?.bot_id || "unknown";

      // Create sync log
      const [syncLog] = await db
        .insert(schema.syncLogs)
        .values({
          integrationId: integration.id,
          status: "in_progress",
          itemsSynced: 0,
          startedAt: new Date(),
        })
        .returning();

      syncLogId = syncLog.id;

      // Get last sync timestamp for incremental sync
      const lastSyncedAt = integration.lastSyncedAt ? new Date(integration.lastSyncedAt) : null;

      const syncMode = lastSyncedAt ? "incremental" : "full";
      console.log(`[NOTION SYNC] Starting ${syncMode} sync for org ${organizationId}`);
      if (lastSyncedAt) {
        console.log(`[NOTION SYNC] Fetching pages modified since ${lastSyncedAt.toISOString()}`);
      }

      // Search pages (with incremental filtering if lastSyncedAt exists)
      const pages = await notionService.searchPages(organizationId, {
        modifiedSince: lastSyncedAt || undefined,
      });

      console.log(`[NOTION SYNC] Found ${pages.length} updated pages`);

      if (pages.length === 0 && !lastSyncedAt) {
        throw new Error(
          "No pages shared with integration. Please share pages in Notion or reconnect."
        );
      }

      // If no updated pages in incremental sync, that's OK
      if (pages.length === 0 && lastSyncedAt) {
        console.log("[NOTION SYNC] No pages modified since last sync - skipping");
        result.success = true;
        result.duration = Date.now() - startTime;

        await db
          .update(schema.syncLogs)
          .set({
            status: "success",
            itemsSynced: 0,
            completedAt: new Date(),
          })
          .where(eq(schema.syncLogs.id, syncLogId));

        return result;
      }

      // Process each page
      for (let i = 0; i < pages.length; i++) {
        const page = pages[i];

        try {
          console.log(`[NOTION SYNC] Processing page ${i + 1}/${pages.length}: "${page.title}"`);
          
          // Update progress
          onProgress?.({
            channelsProcessed: i,
            totalChannels: pages.length,
            messagesProcessed: result.totalMessages,
            messagesEmbedded: result.messagesEmbedded,
            errors: result.errors,
            currentChannel: page.title,
          });

          // Fetch all blocks from page (recursive)
          console.log(`[NOTION SYNC]   Fetching blocks from page...`);
          const blocks = await notionService.getPageBlocks(organizationId, page.id);
          console.log(`[NOTION SYNC]   ✅ Found ${blocks.length} blocks`);

          // Filter out empty blocks
          const validBlocks = blocks.filter((block) => block.text && block.text.trim().length > 0);
          console.log(`[NOTION SYNC]   Valid blocks (non-empty): ${validBlocks.length}`);

          if (validBlocks.length > 0) {
            // Process blocks in batches
            const totalBatches = Math.ceil(validBlocks.length / SYNC_CONFIG.BATCH_SIZE);
            console.log(`[NOTION SYNC]   Embedding ${validBlocks.length} blocks in ${totalBatches} batches...`);
            
            for (let j = 0; j < validBlocks.length; j += SYNC_CONFIG.BATCH_SIZE) {
              const batch = validBlocks.slice(j, j + SYNC_CONFIG.BATCH_SIZE);
              const batchNum = Math.floor(j / SYNC_CONFIG.BATCH_SIZE) + 1;
              
              console.log(`[NOTION SYNC]     Batch ${batchNum}/${totalBatches}: Embedding ${batch.length} blocks...`);
              await this.processNotionBatch(
                batch,
                page,
                organizationId,
                workspaceId,
                workspaceName,
                botId
              );

              result.messagesEmbedded += batch.length;
              result.totalMessages += batch.length;
              console.log(`[NOTION SYNC]     ✅ Batch ${batchNum}/${totalBatches} complete (Total embedded: ${result.messagesEmbedded})`);

              // Update progress
              onProgress?.({
                channelsProcessed: i,
                totalChannels: pages.length,
                messagesProcessed: result.totalMessages,
                messagesEmbedded: result.messagesEmbedded,
                errors: result.errors,
                currentChannel: page.title,
              });
            }
            console.log(`[NOTION SYNC]   ✅ Page "${page.title}" complete - ${validBlocks.length} blocks embedded`);
          } else {
            console.log(`[NOTION SYNC]   ⚠️  No valid content to embed for "${page.title}"`);
          }

          result.channelsProcessed++;
        } catch (error) {
          const errorMsg = `Failed to process page ${page.title}: ${
            error instanceof Error ? error.message : "Unknown error"
          }`;
          console.error(`[NOTION SYNC]   ❌ ${errorMsg}`);
          result.errors.push(errorMsg);
        }
      }

      // Update sync log
      await db
        .update(schema.syncLogs)
        .set({
          status: "success",
          itemsSynced: result.messagesEmbedded,
          completedAt: new Date(),
        })
        .where(eq(schema.syncLogs.id, syncLogId));

      // Update integration lastSyncedAt (only on successful sync)
      await db
        .update(schema.integrations)
        .set({
          lastSyncedAt: new Date(),
          updatedAt: new Date(),
        })
        .where(eq(schema.integrations.id, integration.id));

      result.success = true;
      result.duration = Date.now() - startTime;

      // Log completion summary
      console.log(`[NOTION SYNC] ✅ Sync complete for org ${organizationId}`);
      console.log(`[NOTION SYNC]    Mode: ${syncMode}`);
      console.log(`[NOTION SYNC]    Pages synced: ${result.channelsProcessed}`);
      console.log(`[NOTION SYNC]    Blocks embedded: ${result.messagesEmbedded}`);
      console.log(`[NOTION SYNC]    Duration: ${Math.round(result.duration / 1000)}s`);
      if (result.errors.length > 0) {
        console.log(`[NOTION SYNC]    Errors: ${result.errors.length}`);
      }

      return result;
    } catch (error) {
      // Update sync log as failed
      if (syncLogId) {
        await db
          .update(schema.syncLogs)
          .set({
            status: "failed",
            errorMessage: error instanceof Error ? error.message : "Unknown error",
            completedAt: new Date(),
          })
          .where(eq(schema.syncLogs.id, syncLogId));
      }

      result.errors.push(error instanceof Error ? error.message : "Unknown error");
      result.duration = Date.now() - startTime;
      return result;
    }
  }

  /**
   * Process a batch of Notion blocks: chunk, embed, and dual-write to Pinecone + PostgreSQL
   */
  private async processNotionBatch(
    blocks: any[],
    page: any,
    organizationId: string,
    workspaceId: string,
    workspaceName: string,
    botId: string
  ): Promise<void> {
    try {
      // Check which blocks already exist (by checking first chunk of each block)
      const existingBlocks = await db
        .select({ id: schema.searchContent.id })
        .from(schema.searchContent)
        .where(
          and(
            eq(schema.searchContent.organizationId, organizationId),
            eq(schema.searchContent.source, "notion"),
            eq(schema.searchContent.pageId, page.id)
          )
        );
      
      const existingIds = new Set(existingBlocks.map(b => b.id));
      
      // Filter out blocks that already exist
      // Notion blocks with same ID = same content (Notion API ensures this)
      const newOrModifiedBlocks = blocks.filter(block => {
        const firstChunkId = `notion-${page.id}-${block.id}-chunk-0`;
        return !existingIds.has(firstChunkId);
      });
      
      if (newOrModifiedBlocks.length === 0) {
        console.log(`   ⏭️  All ${blocks.length} blocks already up-to-date - skipping`);
        return;
      }
      
      if (newOrModifiedBlocks.length < blocks.length) {
        console.log(`   📊 ${newOrModifiedBlocks.length} new/modified, ${blocks.length - newOrModifiedBlocks.length} unchanged`);
      }

      // Use structure-aware chunking for Notion
      // This preserves headings, code blocks, and creates rich metadata
      const smartChunks = notionChunkingService.chunkNotionBlocks(
        newOrModifiedBlocks,
        page.title
      );

      const texts = smartChunks.map((chunk) => chunk.text);
      const embeddings = await embeddingService.embedTexts(texts);

      const vectors = smartChunks.map((chunk, idx) => {
        // Get the first block referenced by this chunk for timestamps
        const firstBlockId = chunk.block_ids[0];
        const firstBlock = newOrModifiedBlocks.find(b => b.id === firstBlockId);
        const editedDate = firstBlock ? new Date(firstBlock.last_edited_time) : new Date();
        
        // Safety check
        if (!chunk.block_ids || chunk.block_ids.length === 0) {
          console.warn(`[NOTION SYNC] ⚠️  Chunk ${idx} has no block_ids!`, chunk);
        }

        return {
          id: `notion-${page.id}-${chunk.section_id}-chunk-${chunk.chunkIndex}`,
          values: embeddings[idx],
          metadata: {
            text: chunk.text,
            source: "notion",
            source_type: "block",

            page_id: page.id,
            page_title: page.title,
            page_url: page.url,

            // Original block metadata (for backward compat)
            block_id: chunk.block_ids[0], // Primary block
            block_type: firstBlock?.type || "unknown",

            // NEW: Structure-aware metadata
            section_path: JSON.stringify(chunk.section_path), // Store as JSON string
            section_title: chunk.section_title,
            section_id: chunk.section_id,
            ...(chunk.heading_level !== null && { heading_level: chunk.heading_level }),

            chunk_type: chunk.chunk_type,
            has_code: chunk.has_code,
            has_table: chunk.has_table,
            has_list: chunk.has_list,
            
            ...(chunk.code_language && { code_language: chunk.code_language }),

            chunk_index: chunk.chunkIndex,
            total_chunks: chunk.totalChunks,
            is_chunked: chunk.totalChunks > 1,

            created_by_id: page.created_by_id,
            last_edited_by_id: page.last_edited_by_id,

            created_time: firstBlock?.created_time || new Date().toISOString(),
            last_edited_time: firstBlock?.last_edited_time || new Date().toISOString(),
            timestamp: Math.floor(editedDate.getTime() / 1000),

            date: editedDate.toISOString().split("T")[0],
            year: editedDate.getFullYear(),
            month: editedDate.getMonth() + 1,

            organization_id: organizationId,
            workspace_id: workspaceId,
            workspace_name: workspaceName,
            bot_id: botId,

            ...(page.parent_page_id && { parent_page_id: page.parent_page_id }),
            ...(page.parent_database_id && { parent_database_id: page.parent_database_id }),
          },
        };
      });

      const namespace = `org-${organizationId}`;

      // DUAL-WRITE: Store in both Pinecone (semantic) and PostgreSQL (keyword)
      await vectorService.upsertVectors(vectors, namespace);

      // Transform vectors to PostgreSQL format and upsert (handles duplicates)
      const searchContentRecords = vectors.map((v) =>
        this.transformVectorToSearchContent(v, organizationId)
      );

      // Use onConflictDoUpdate to handle re-syncing of updated pages/blocks
      await db
        .insert(schema.searchContent)
        .values(searchContentRecords)
        .onConflictDoUpdate({
          target: schema.searchContent.id,
          set: {
            text: sql`EXCLUDED.text`,
            pageTitle: sql`EXCLUDED.page_title`,
            // Update structure-aware metadata on re-sync
            sectionPath: sql`EXCLUDED.section_path`,
            sectionTitle: sql`EXCLUDED.section_title`,
            chunkType: sql`EXCLUDED.chunk_type`,
            hasCode: sql`EXCLUDED.has_code`,
            hasTable: sql`EXCLUDED.has_table`,
            hasList: sql`EXCLUDED.has_list`,
            codeLanguage: sql`EXCLUDED.code_language`,
            timestamp: sql`EXCLUDED.timestamp`,
            date: sql`EXCLUDED.date`,
            updatedAt: new Date(),
          },
        });
    } catch (error) {
      console.error("[NOTION SYNC] ❌ Batch processing error:", error);
      console.error("[NOTION SYNC] Error details:", error instanceof Error ? error.message : String(error));
      if (error instanceof Error && error.stack) {
        console.error("[NOTION SYNC] Stack trace:", error.stack);
      }
      throw new Error("Failed to process Notion block batch", { cause: error });
    }
  }
}

export const ingestionService = new IngestionService();
