import { BaseTool, ToolContext, ToolParameters, ToolResult } from "./base.tool";

/**
 * Text Response Tool
 *
 * Generates conversational text responses to general questions.
 * This is the default tool for answering questions that don't require
 * specialized capabilities like knowledge search, expert matching, or UI guidance.
 *
 * Use cases:
 * - General questions: "What is our company mission?"
 * - Explanations: "How does our PTO policy work?"
 * - Clarifications: "What did you mean by that?"
 * - Chitchat: "How are you?"
 *
 * The response is generated by the AI model and is streamable,
 * meaning it can be sent to the user word-by-word as it's generated.
 */
export class RespondTextTool extends BaseTool {
  name = "respond_with_text";

  description = `
    Respond to general questions with helpful, conversational text answers.
    Use this tool for questions about company information, policies, explanations,
    clarifications, and general conversation. This is the default tool when other
    specialized tools (knowledge search, expert finder, UI guidance) are not needed.
  `.trim();

  parameters: ToolParameters = {
    type: "object",
    properties: {
      response: {
        type: "string",
        description: "The helpful, friendly text response to the user's question",
      },
    },
    required: ["response"],
  };

  /**
   * Execute the text response tool
   *
   * For this tool, the AI has already generated the response text,
   * so we simply return it in a streamable format.
   *
   * @param args - Contains the generated response text
   * @param context - Conversation context (not used for simple text responses)
   * @returns Tool result with text content that can be streamed
   */
  async execute(args: { response: string }, _context: ToolContext): Promise<ToolResult> {
    // Validate arguments
    this.validate(args);

    // For text responses, AI has already generated the content
    // We just need to format it as a streamable result
    return {
      messageType: "text",
      content: args.response,
      streamable: true,
    };
  }
}
